name: LAMS

on:
  pull_request:
    branches: [ main ]
  push:
  workflow_dispatch:

jobs:
  lams_job:
    runs-on: ubuntu-latest
    name: LAMS LookML Linter Job
    steps:
    - name: Checkout your LookML
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - name: Install LAMS
      run: npm install -g @looker/look-at-me-sideways@3
    - name: Run LAMS
      run: lams --reporting=no
    - name: Install Spectacles
      run: pip install spectacles
    - name: Run Spectacles Tests
      run: |
        spectacles connect \
          --base-url https://nubalia.cloud.looker.com \
          --client-id 3YwXp8CmR8ZmgwTQg9C2 \
          --client-secret jMG5Y9CmT7ZDPRDYSnPTdjmF

        spectacles sql \
          --project pruebas_laura \
          --branch ${{ github.head_ref }} \
          --remote-branch main \
          --base-url nubalia.cloud.looker.com \
          --client-id 3YwXp8CmR8ZmgwTQg9C2 \
          --client-secret jMG5Y9CmT7ZDPRDYSnPTdjmF
